spring:
  application:
    name: "oson"

  datasource:
   url: jdbc:h2:mem:testdb
   driverClassName: org.h2.Driver
   username: oson
   password: oson123!

   jpa:
    database-platform: org.hibernate.dialect.H2Dialect